image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/filestash
  tag: latest@sha256:a541026ec3eaaa67cc568b4fffd006460965eb6a408a512d841d1c06213ea9eb
persistence:
  appdata:
    enabled: true
    mountPath: "/app/data/state"
securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 8334
portal:
  open:
    enabled: true
