image:
  repository: hotio/jackett
  pullPolicy: Always
  tag: latest
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9117
        port: 9117
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/UI/Login"
            readiness:
              path: "/UI/Login"
            startup:
              path: "/UI/Login"
