image:
  pullPolicy: IfNotPresent
  repository: wallabag/wallabag
  tag: 2.6.5@sha256:0bd39342debda9a90500f57975aab89780d3048fcfecf9260caf4e171a7ec889
persistence:
  appdata:
    enabled: true
    mountPath: "/var/www/wallabag/data"
  appimages:
    enabled: true
    mountPath: "/var/www/wallabag/web/assets/images"
  phpconfig:
    enabled: true
    mountPath: "/etc/php81/php.ini"
  fpmconfig:
    enabled: true
    mountPath: "/etc/php81/php-fpm.conf"
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  container:
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        port: 80
portal:
  open:
    enabled: true
