image:
  pullPolicy: Always
  repository: tccr.io/truecharts/filestash
  tag: latest
persistence:
  appdata:
    enabled: true
    mountPath: "/app/data/state"
securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 8334
portal:
  open:
    enabled: true
