image:
  repository: tccr.io/truecharts/memcached
  pullPolicy: IfNotPresent
  tag: v1.6.20@sha256:6e11823db1555e766c5eda1b7725f4cc5cc5513da404644541d38a8432820117

service:
  main:
    ports:
      main:
        port: 11211
        protocol: tcp
        targetPort: 11211

portal:
  open:
    enabled: false

manifestManager:
  enabled: false
