apiVersion: v2
appVersion: "0.20.4145"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.9.2
deprecated: false
description: placeholder app
home: https://truecharts.org/charts/stable/jackett
icon: https://truecharts.org/img/hotlink-ok/chart-icons/jackett.png
keywords:
  - placeholder
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: placeholder
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/jackett
  - https://github.com/Jackett/Jackett
type: application
version: 0.0.1
annotations:
  truecharts.org/catagories: |
    - media
    - test
  truecharts.org/SCALE-support: "true"
