image:
  pullPolicy: Always
  repository: adnanyaqoobvirk/webhook
  tag: latest
persistence:
  hooks:
    enabled: true
    mountPath: "/etc/webhook"
  cache:
    enabled: true
    mountPath: "/cache"
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            startup:
              type: tcp
            readiness:
              type: tcp
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  container:
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        port: 80
        targetPort: 9000
portal:
  open:
    enabled: true
